version: "3.8"

services:
  chat-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - WATCHDOG_TIMEOUT=300
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
